name: read time sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ github.repository }}
      YEAR: ${{ vars.YEAR }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Remove folder
        run: rm -rf ./OUT_FOLDER
      - name: Set default year if not provided
        run: echo "YEAR=$(date +"%Y")" >> $GITHUB_ENV
        if: env.YEAR == ''
      - name: weread heatmap
        run: |
          github_heatmap weread  --year $YEAR  --me "${{secrets.NAME}}" --without-type-name --background-color=${{ vars.background_color||'#FFFFFF'}} --track-color=${{ vars.track_color||'#ACE7AE'}} --special-color1=${{ vars.special_color||'#69C16E'}} --special-color2=${{ vars.special_color2||'#549F57'}} --dom-color=${{ vars.dom_color||'#EBEDF0'}} --text-color=${{ vars.text_color||'#000000'}}
      - name: Rename weread.svg to a random name
        run: |
          cd OUT_FOLDER
          find . -type f ! -name "weread.svg" -exec rm -f {} +
          cd ..
          RANDOM_FILENAME=$(uuidgen).svg
          mv ./OUT_FOLDER/weread.svg ./OUT_FOLDER/$RANDOM_FILENAME
          echo "Renamed file to $RANDOM_FILENAME"
      - name: read time sync
        run: |
          read_time