name: weread note sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ github.repository }}
      TOKEN: ${{ secrets.TOKEN }}
      BOOK_DATABASE_NAME: ${{ vars.BOOK_DATABASE_NAME }}
      AUTHOR_DATABASE_NAME: ${{ vars.AUTHOR_DATABASE_NAME }}
      CATEGORY_DATABASE_NAME: ${{ vars.CATEGORY_DATABASE_NAME }}
      BOOKMARK_DATABASE_NAME: ${{ vars.BOOKMARK_DATABASE_NAME }}
      REVIEW_DATABASE_NAME: ${{ vars.REVIEW_DATABASE_NAME }}
      CHAPTER_DATABASE_NAME: ${{ vars.CHAPTER_DATABASE_NAME }}
      YEAR_DATABASE_NAME: ${{ vars.YEAR_DATABASE_NAME }}
      WEEK_DATABASE_NAME: ${{ vars.WEEK_DATABASE_NAME }}
      MONTH_DATABASE_NAME: ${{ vars.MONTH_DATABASE_NAME }}
      DAY_DATABASE_NAME: ${{ vars.DAY_DATABASE_NAME }}
      WEREAD2NOTION: ${{ vars.WEREAD2NOTION }}
      STATUS_COMPLETE: ${{ vars.STATUS_COMPLETE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: weread2notion sync
        if: ${{ vars.WEREAD2NOTION == 'true' }}
        run: |
          weread2notion
      - name: weread book sync
        if: ${{ vars.WEREAD2NOTION != 'true' }}
        run: |
          book
      - name: weread sync
        if: ${{ vars.WEREAD2NOTION != 'true' }}
        run: |
          weread
      - name: fix sync
        # Corrected indentation for the 'if' condition
        if: ${{ vars.WEREAD2NOTION != 'true' }}
        run: |
          fix